# Generated by Django 4.1.1 on 2022-09-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="question", new_name="notice",
        ),
    ]
